# Site settings
title: 张春明
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'https://zsfzbc.github.io/blog'
baseurl: '/blog'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'zhangcm'
  email: 1406548180@qq.com
  twitter_username: zsfzbc
  facebook_username: zsfzbc
  github_username:  zsfzbc
  linkedin_username:  zsfzbc

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
